--- 
- name: Create a snapshot of instance 
  hosts: localhost 

  tasks: 
    - name: Gather EC2 facts
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": demo-server-0
          instance-state-name: ["running"]
      register: instances

    - name: Print Instance Id
      ansible.builtin.debug:
        msg: "Instance : {{ instances.instances.0.instance_id }}"

    - name: Store Instance Id in fact
      ansible.builtin.set_fact:
        instance_id: "{{ instances.instances.0.instance_id }}"

    - name: Create Snapshot of volume mounted on device_name attached to instance_id
      amazon.aws.ec2_snapshot:
        instance_id: "{{ instance_id }}"
        device_name: "/dev/sda1"