--- 
- name: Get lifecycle info for s3 bucket 
  hosts: localhost 
  gather_facts: no 

  vars:
    bucket_name: "{{ survey_bucket_name | default('jpc-s3-demo') }}" 

  tasks:
    - name: Retrieve lifecycle config for s3 bucket 
      amazon.aws.s3_bucket_info:
        name_filter: "{{ bucket_name }}"
        bucket_facts:
          bucket_lifecycle_configuration: true
          bucket_encryption: true
      register: bucket_info 

    - debug:
        var: bucket_info