--- 
- name: Create an S3 bucket and set a lifecycle rule 
  hosts: localhost 
  gather_facts: no 

  vars:
    bucket_name: "{{ survey_bucket_name | default('jpc-s3-demo') }}" 

  tasks:
    - name: Create S3 Bucket 
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        encryption: "aws:kms"
        state: present

    - name: Add some files
      amazon.aws.s3_object:
        bucket: "{{ bucket_name }}"
        object: "{{ item.object }}"
        src: "{{ item.src }}"
        mode: put
      loop: 
        - { object: create-ami.yml, src: "create-ami.yml" }
        - { object: rhel-updates.yml, src: "rhel-updates.yml" }
        - { object: rhel-instance.yml, src: "rhel-instance.yml" }
        - { object: /ansible/create-ami.yml, src: "create-ami.yml" }
        - { object: /ansible/rhel-updates.yml, src: "rhel-updates.yml" }
        - { object: /ansible/rhel-instance.yml, src: "rhel-instance.yml" }

    - name: Set a lifecycle rule to transition all items with a prefix of /ansible/ to glacier after 7 days and then delete after 90 days
      community.aws.s3_lifecycle:
        name: "{{ bucket_name }}"
        transition_days: 7
        expiration_days: 90
        prefix: ansible/
        status: enabled
        state: present