- name: Check for instances without a specific tag
  hosts: localhost 

  vars:
    search_value: "{{ survey_search_value | default('Ansible') }}"
  tasks:
    - name: Get list of all EC2 Instances except termininated ones 
      amazon.aws.ec2_instance_info:
        filters:
          instance-state-name: ["running","pending","shutting-down","stopping","stopped"]
      register: ec2_instances

    - name: Print list of instances without a(n) {{ search_value }} tag
      ansible.builtin.debug:
        msg: "{{ ec2_instances | community.general.json_query(query1) | difference(ec2_instances | community.general.json_query(query2)) }}"
      vars:
        query1: "instances[*].tags.Name"
        query2: "instances[?contains(keys(tags),'{{ search_value }}')].tags.Name"