---
- name: Wait for connection to be available
  hosts: aap 
  gather_facts: false 

  vars:
    ansible_connection: ansible.builtin.aws_ssm
    ansible_aws_ssm_bucket_name: jpc-ssm-test
    # ansible_aws_ssm_region: us-east-1
    # # When the S3 bucket isn't in the same region as the Instance
    # # Explicitly setting the addressing style to 'virtual' may be necessary
    # # https://repost.aws/knowledge-center/s3-http-307-response
    # ansible_aws_ssm_s3_addressing_style: virtual

    # # Move the tmp path to a globally writable location
    # ansible_remote_tmp: /tmp/.ansible-{{ ansible_user | default('ssm-user') }}/tmp
    ansible_user: ssm-user 
    
  tasks:
    - name: Test that we can do something on these systems 
      ansible.builtin.ping: 