---
- name: Teardown AWS demo resources 
  hosts: localhost
  gather_facts: no

  tasks:

    - name: fetch infra info 
      ansible.builtin.include_role:
        name: aws_infra_info

    - name: Deprovision Demo EC2 Instances
      amazon.aws.ec2_instance:
        state: absent
        filters:
          "tag:demo": Ansible 
          instance-state-name: "*" 
        wait: yes

    - name: Get caller info 
      amazon.aws.aws_caller_info:
      register: caller 

    - name: Get snapshot id 
      amazon.aws.ec2_snapshot_info:
        filters:
          owner-id: "{{ caller.account }}"
      register: snapshots

    - amazon.aws.ec2_snapshot:
        snapshot_id: "{{ snapshots.snapshots.0.snapshot_id }}"
        state: absent
      when: snapshots.snapshots | length > 0

    - name: Remove subnet route table 
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        route_table_id: "{{ vpc_route_info.route_tables[0].route_table_id }}"
        lookup: id
        state: absent
      when: vpc_route_info.route_tables

    - name: Remove subnets 
      amazon.aws.ec2_vpc_subnet:
        state: absent 
        cidr: 10.0.0.0/16
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      when: vpc_info.vpcs

    - name: Remove security groups
      amazon.aws.ec2_security_group: 
        state: absent
        vpc_id: "{{ vpc_info.vpcs[0].id }}"
        group_id: "{{ sec_info.security_groups[0].group_id }}"
      when: sec_info.security_groups 

    - name: Remove Internet gateway 
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].id }}"
        #internet_gateway_id: "{{ igw_info.internet_gateways[0].internet_gateway_id }}"
        state: absent
      when: igw_info.internet_gateways

    - name: Remove VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ vpc_info.vpcs[0].id }}"
        state: absent
      when: vpc_info.vpcs

    - name: Remove AWS Keypair 
      amazon.aws.ec2_key: 
        name: "ansible-demo-key"
        state: absent